### ISSUE TITLE
Missing code for some baseline models in NASBench201 

### ISSUE THREAD

**Issue by kyuabacus** [MiaoZhang0525/NSAS_FOR_CVPR#1]
Hi,

Thanks for your great work and extending our WPL loss into one-shot NAS in a general way! 

I am reading your code and would like to test the NASBench201 implementation. However, it seems like I cannot find some files. For example, the notebook `NSAS_Bench201/exps/algos/random_NAS_NSAS_3_0.2_seed0.ipynb`. In the `search_func`, there is a call of `network.module.arch_diver(operations_random)`. I did a global search for `def arch_diver` but nothing returns. 

I further visit the code of the implementation of NSAS super-net, and goes to the `get_cell_based_tiny_net` method in `lib/models/cell_searchs/__init__.py`. Here, there is a `from .l2s_cell_searchs import nas_super_nets`. Yet, there is no folder or file called `l2s_cell_searchs`. Other files under `cell_searchs` seem to be identical as the baseline NASBench201 implementation. I will be really appreciated if you could point me to the implementation of NSAS for NB201 or other search spaces. 

Thanks in advance! 
Kaicheng

**Comment by miaozhang0525** [comment]
> Hi,
> 
> Thanks for your great work and extending our WPL loss into one-shot NAS in a general way!
> 
> I am reading your code and would like to test the NASBench201 implementation. However, it seems like I cannot find some files. For example, the notebook `NSAS_Bench201/exps/algos/random_NAS_NSAS_3_0.2_seed0.ipynb`. In the `search_func`, there is a call of `network.module.arch_diver(operations_random)`. I did a global search for `def arch_diver` but nothing returns.
> 
> I further visit the code of the implementation of NSAS super-net, and goes to the `get_cell_based_tiny_net` method in `lib/models/cell_searchs/__init__.py`. Here, there is a `from .l2s_cell_searchs import nas_super_nets`. Yet, there is no folder or file called `l2s_cell_searchs`. Other files under `cell_searchs` seem to be identical as the baseline NASBench201 implementation. I will be really appreciated if you could point me to the implementation of NSAS for NB201 or other search spaces.
> 
> Thanks in advance!
> Kaicheng

Hi, Kaicheng,

Sorry for the confusion. I have updated the lib in the NASBENCH201, please check it.

Cheers,
Miao

**Comment by kyuabacus** [comment]
Thanks Miao, saw the changes. Will play around with it! 

Best,
Kaicheng
